### ISSUE TITLE
Registration Crash Bug

### ISSUE THREAD

**Issue by chan-kelv** [ubclaunchpad/driver#106]
[registration error.txt](https://github.com/ubclaunchpad/driver/files/1053046/registration.error.txt)

Crash when registering new user

> 06-05 12:59:50.243 25910-25910/com.android.ubclaunchpad.driver E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                 Process: com.android.ubclaunchpad.driver, PID: 25910
                                                                                 java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
                                                                                     at com.google.android.gms.internal.zzaix$zza.zzaE(Unknown Source)
                                                                                     at com.google.android.gms.internal.zzaix.zzaw(Unknown Source)
                                                                                     at com.google.android.gms.internal.zzaix.zzav(Unknown Source)
                                                                                     at com.google.firebase.database.DatabaseReference.zza(Unknown Source)
                                                                                     at com.google.firebase.database.DatabaseReference.setValue(Unknown Source)
                                                                                     at com.android.ubclaunchpad.driver.UI.RegisterActivity$1.onAuthStateChanged(RegisterActivity.java:66)
                                                                                     at com.google.firebase.auth.FirebaseAuth$2.run(Unknown Source)
                                                                                     at android.os.Handler.handleCallback(Handler.java:751)
                                                                                     at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                     at android.os.Looper.loop(Looper.java:154)
                                                                                     at android.app.ActivityThread.main(ActivityThread.java:6688)
                                                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468)
                                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358)
                                                                                  Caused by: java.lang.reflect.InvocationTargetException
                                                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                                                     at com.google.android.gms.internal.zzaix$zza.zzaE(Unknown Source) 
                                                                                     at com.google.android.gms.internal.zzaix.zzaw(Unknown Source) 
                                                                                     at com.google.android.gms.internal.zzaix.zzav(Unknown Source) 
                                                                                     at com.google.firebase.database.DatabaseReference.zza(Unknown Source) 
                                                                                     at com.google.firebase.database.DatabaseReference.setValue(Unknown Source) 
                                                                                     at com.android.ubclaunchpad.driver.UI.RegisterActivity$1.onAuthStateChanged(RegisterActivity.java:66) 
                                                                                     at com.google.firebase.auth.FirebaseAuth$2.run(Unknown Source) 
                                                                                     at android.os.Handler.handleCallback(Handler.java:751) 
                                                                                     at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                                                     at android.os.Looper.loop(Looper.java:154) 
                                                                                     at android.app.ActivityThread.main(ActivityThread.java:6688) 
                                                                                     at java.lang.reflect.Method.invoke(Native Method) 
                                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468) 
                                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358) 
                                                                                  Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference
                                                                                     at com.android.ubclaunchpad.driver.models.User.getNumFreeSeats(User.java:65)
                                                                                     at java.lang.reflect.Method.invoke(Native Method) 
                                                                                     at com.google.android.gms.internal.zzaix$zza.zzaE(Unknown Source) 
                                                                                     at com.google.android.gms.internal.zzaix.zzaw(Unknown Source) 
                                                                                     at com.google.android.gms.internal.zzaix.zzav(Unknown Source) 
                                                                                     at com.google.firebase.database.DatabaseReference.zza(Unknown Source) 
                                                                                     at com.google.firebase.database.DatabaseReference.setValue(Unknown Source) 
                                                                                     at com.android.ubclaunchpad.driver.UI.RegisterActivity$1.onAuthStateChanged(RegisterActivity.java:66) 
                                                                                     at com.google.firebase.auth.FirebaseAuth$2.run(Unknown Source) 
                                                                                     at android.os.Handler.handleCallback(Handler.java:751) 
                                                                                     at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                                                     at android.os.Looper.loop(Looper.java:154) 
                                                                                     at android.app.ActivityThread.main(ActivityThread.java:6688) 
                                                                                     at java.lang.reflect.Method.invoke(Native Method) 
                                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468) 
                                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358) 
06-05 12:59:58.195 25910-25956/com.android.ubclaunchpad.driver E/DynamiteModule: Failed to load module descriptor class: Didn't find class "com.google.android.gms.dynamite.descriptors.com.google.firebase.auth.ModuleDescriptor" on path: DexPathList[[zip file "/data/app/com.android.ubclaunchpad.driver-1/base.apk", zip file "/data/app/com.android.ubclaunchpad.driver-1/split_lib_dependencies_apk.apk", zip file "/data/app/com.android.ubclaunchpad.driver-1/split_lib_slice_0_apk.apk", zip file "/data/app/com.android.ubclaunchpad.driver-1/split_lib_slice_1_apk.apk", zip file "/data/app/com.android.ubclaunchpad.driver-1/split_lib_slice_2_apk.apk", zip file "/data/app/com.android.ubclaunchpad.driver-1/split_lib_slice_3_apk.apk", zip file "/data/app/com.android.ubclaunchpad.driver-1/split_lib_slice_4_apk.apk", zip file "/data/app/com.android.ubclaunchpad.driver-1/split_lib_slice_5_apk.apk", zip file "/data/app/com.android.ubclaunchpad.driver-1/split_lib_slice_6_apk.apk", zip file "/data/app/com.android.ubclaunchpad.driver-1/split_lib_slice_7_apk.apk", zip file "/data/app/com.android.ubclaunchpad.driver-1/split_lib_slice_8_apk.apk", zip file "/data/app/com.android.ubclaunchpad.driver-1/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/com.android.ubclaunchpad.driver-1/lib/arm64, /system/lib64, /vendor/lib64]]

**Comment by jsondoo** [comment]
This is now fixed by sherry in https://github.com/ubclaunchpad/driver/pull/107
